.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. globe_qt test_globe_qt
clean: FORCE
	$(MAKE) -C .. globe_qt_clean test_globe_qt_clean
check: FORCE
	$(MAKE) -C .. test_globe_qt_check
globe-qt globe-qt.exe: FORCE
	 $(MAKE) -C .. globe_qt
apk: FORCE
	$(MAKE) -C .. globe_qt_apk
